services:
  - type: web
    name: journaling-app
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_MAX_THREADS
        value: 5
      - key: RAILS_LOG_LEVEL
        value: info
      - key: WEB_CONCURRENCY
        value: 2
      - key: PORT
        value: 3000
      - key: OPENAI_API_KEY
        sync: false
